
name: test-CI-CD-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "anton-test-github-actions"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "MyFlaskEnv"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches:
      - main
      
jobs:
  ci_pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone repo
      uses: actions/checkout@v1
      
    - name: Create ZIP deployment package
      run : zip -r ${{ env.EPLOY_PACKAGE_NAME }} ./ -x *.git*
      
      
    
