
name: test-CI-CD-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "anton-test-github-actions"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "MyFlaskEnv"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches:
      - main
      
jobs:
  ci_pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone repo
      uses: actions/checkout@v1
      
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_ACCESS_SECRET_KEY }}
        aws-region           : ${{ env.AWS_REGION_NAME }}
        
    - name: Copy Deployment package to S3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: Print happy message for CI finished successfully
      run : echo "CI Pipeline part finished successfully"
